#!/bin/sh
#
# Requires etckeeper and, wget or curl
#
# Defined Constants
REPOSITORY='http://raw.githubusercontent.com/CVBruce/SoftwareUpdate/master/'

# Discovered Constants
CURL=`which curl`
SCRIPT=$0
SCRIPT_CKSUM=`cksum $0 | cut -d' ' -f1`
SCRIPT_NAME=`basename $0`
WGET=`which wget`

# Check to ensure that this script is being executed by someone with root authority.
ID=`id -u`
if [ $ID != 0 ] 
then
        echo;
        echo "--->  You must run `basename $0` as root, or via sudo.";
        echo;
        exit 4;
fi
#
# Self update
#
cd /tmp

if [ -e $WGET ]
then 
	sudo $WGET --quiet $REPOSITORY/$SCRIPT_NAME;
elif [ -e $CURL ]
then 
	sudo $CURL -O --silent $REPOSITORY/$SCRIPT_NAME;
else
        echo;
	echo "---> Can't find wget or curl. Unable to auto-install $SCRIPT_NAME"
        echo;
fi
NEW_CKSUM=`cksum $SCRIPT_NAME | cut -d' ' -f1`

if [ "$NEW_CKSUM" = "" ] 
then
        echo;
	echo "---> $SCRIPT_NAME not found in repository.";
        echo;
fi

if [ "$NEW_CKSUM" != "$SCRIPT_CKSUM" ]
then
	sudo cp $SCRIPT_NAME $SCRIPT;
	sudo chmod 755 $SCRIPT;
        echo;
	echo "---> $SCRIPT_NAME has been updated. Executing the updated version....";
        echo;
	exec $SCRIPT;
else 
        echo;
	echo "---> $SCRIPT_NAME is current version.";
        echo;
fi

# Remove downloaded Script.
rm /tmp/$SCRIPT_NAME;

#
# Create a list of all installed software in a place that etckeeper will archive
# 
if [ -e /usr/bin/dpkg ]
then
        echo;
	echo "---> Creating list of installed software.";
        echo;
	/usr/bin/dpkg -l >/etc/dpkg/dpkg.list.txt;
fi
#
# Backup all changed files in /etc
#
if [ -e /usr/bin/etckeeper ]
then
	#EtcKeeper commit
        echo;
	echo "---> Backing up changed files in /etc.";
        echo;
	/usr/bin/etckeeper post-install;
	/usr/bin/etckeeper commit auto;
fi
#
# Run apt-get update, dist-upgrade, autoremove, autoclean
#
if [ -e /usr/bin/apt-get ]
then
        echo;
	echo "---> Running apt-get update, dist-upgrade, autoremove, autoclean.";
        echo;
	apt-get update --assume-yes --quiet &&\
	apt-get dist-upgrade --assume-yes --quiet &&\
	apt-get autoremove --assume-yes --quiet &&\
	apt-get autoclean --assume-yes --quiet;
	echo ;
	echo "---> Update Complete.";
	echo ;
fi
#
# For Beagle Bone Black, check for and instll kernel updates
#
if [ -e /opt/scripts/tools/update_kernel.sh ]
then
        echo;
	echo "---> Updating Beagle Bone Black kernel.";
        echo;
	/opt/scripts/tools/update_kernel.sh;
#
# For Pine64, check for and install kernel and uboot updates
#
elif [ -e /usr/local/sbin/pine64_update_kernel.sh ]
then
        echo;
	echo "---> Updating Pine64 Uboot and Kernel.";
        echo;
	/usr/local/sbin/pine64_update_uboot.sh;
	/usr/local/sbin/pine64_update_kernel.sh;
fi
#
# Reboot to make updates effective.
#
if [ $? = 0 ]
then	
        echo;
	echo "--->Rebooting";
        echo;
	/sbin/shutdown -r +1 &
fi
